services:
  - type: web
    name: whats-for-lunch
    env: node
    buildCommand: ./render-build.sh
    startCommand: node dist/index.js
    staticPublishPath: ./client
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000